// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emcppynoiprlowuowgan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtY3BweW5vaXBybG93dW93Z2FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzMTU5MjIsImV4cCI6MjA5Njg5MTkyMn0.EL1ZMVlnTnZVZ0xb_QrAtIrZybznPWPt3Jn3YLf-xh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});